// VARIABILE PER IL CALCOLO DELLA DISTANZA DEI PIN
export const list_markers = [];
//  export const iconMarker = new L.Icon({
//      iconUrl:'../assets/img/location.png',
//      iconAnchor:[24,48],
//      iconSize:[48,48]
//  });

// VARIABILI DI MAPPATURA
export const maxDistance = 8;
export const maxSquare = 50000; // AREA MASSIMA SELEZIONABILE 150.000mq = 15ha = 0.15km2
export const densityOfMarker = 2000;
export const debugMode = false;
export const maxAddressCount = 8; // NUMERO MAX DI INDIRIZZI SELEZIONABILI
export const squareSelected = 0;
export const currentLocation = false;

// LISTA DEGLI INDIRIZZI
export const list_address = [];
export const lista_indirizzi_a_catasto = [];

export const zoneName = "";

// RICARICA LA ZONA DI RICERCA
export const refreshZone = false;

// URL PATH COMUNI ITALIANI 25/07/2024
export const PATH_URL_COMUNI_ITALIANI = "src/utils/txt/listacomuni.txt";

export const toponimi = [
  { id: "0#TUTTI", value: "TUTTI" },
  { id: "300#ACCESSO", value: "ACCESSO" },
  { id: "301#ACCESSO A CORSO", value: "ACCESSO A CORSO" },
  { id: "750#ACCESSO A VIA", value: "ACCESSO A VIA" },
  { id: "302#ACCESSO ALLA PIAZZA", value: "ACCESSO ALLA PIAZZA" },
  { id: "751#ACCESSO ALLA SALITA", value: "ACCESSO ALLA SALITA" },
  { id: "303#ACCESSO ALLA VIA", value: "ACCESSO ALLA VIA" },
  { id: "305#ACCESSO PRIVATO", value: "ACCESSO PRIVATO" },
  { id: "306#ACCESSO STRADA", value: "ACCESSO STRADA" },
  { id: "307#ACCESSO TRAVERSA", value: "ACCESSO TRAVERSA" },
  { id: "304#ACCESSO VIALE", value: "ACCESSO VIALE" },
  { id: "308#ALLEE", value: "ALLEE" },
  { id: "309#ALVEO", value: "ALVEO" },
  { id: "268#ALZAIA", value: "ALZAIA" },
  { id: "752#ALZAIA DI VIA", value: "ALZAIA DI VIA" },
  { id: "1#ALZATA", value: "ALZATA" },
  { id: "2#ANDRONA", value: "ANDRONA" },
  { id: "310#ANDRONE", value: "ANDRONE" },
  { id: "311#ANGIPORTO", value: "ANGIPORTO" },
  { id: "4#ARCHIVOLTO", value: "ARCHIVOLTO" },
  { id: "6#ARCO", value: "ARCO" },
  { id: "753#ARCO DI VIA", value: "ARCO DI VIA" },
  { id: "312#ARGINE", value: "ARGINE" },
  { id: "313#ARGINE DESTRO", value: "ARGINE DESTRO" },
  { id: "314#ARGINE DI CANALE", value: "ARGINE DI CANALE" },
  { id: "315#ARGINE SINISTRO", value: "ARGINE SINISTRO" },
  { id: "8#ASCENSORE", value: "ASCENSORE" },
  { id: "10#ATRIO", value: "ATRIO" },
  { id: "316#AUTOSTRADA", value: "AUTOSTRADA" },
  { id: "317#AVENUE", value: "AVENUE" },
  { id: "49#B.GO", value: "B.GO" },
  { id: "12#BACINO", value: "BACINO" },
  { id: "14#BAGLIO", value: "BAGLIO" },
  { id: "318#BALUARDO", value: "BALUARDO" },
  { id: "16#BANCHINA", value: "BANCHINA" },
  { id: "319#BARRIERA", value: "BARRIERA" },
  { id: "320#BASTIONE", value: "BASTIONE" },
  { id: "18#BASTIONI", value: "BASTIONI" },
  { id: "321#BASTIONI DI PORTA", value: "BASTIONI DI PORTA" },
  { id: "322#BATTERIA", value: "BATTERIA" },
  { id: "754#BELVEDERE", value: "BELVEDERE" },
  { id: "323#BISAGNO", value: "BISAGNO" },
  { id: "755#BIVIO", value: "BIVIO" },
  { id: "324#BOCCA", value: "BOCCA" },
  { id: "20#BORGATA", value: "BORGATA" },
  { id: "22#BORGHETTO", value: "BORGHETTO" },
  { id: "24#BORGO", value: "BORGO" },
  { id: "756#BORGOLOCO", value: "BORGOLOCO" },
  { id: "325#BOULEVARD", value: "BOULEVARD" },
  { id: "27#C.SO", value: "C.SO" },
  { id: "326#CA'", value: "CA'" },
  { id: "327#CALA", value: "CALA" },
  { id: "26#CALATA", value: "CALATA" },
  { id: "328#CALETTA", value: "CALETTA" },
  { id: "28#CALLE", value: "CALLE" },
  { id: "329#CALLE DESTRA", value: "CALLE DESTRA" },
  { id: "757#CALLE DI VIALE", value: "CALLE DI VIALE" },
  { id: "758#CALLE ESTERNA", value: "CALLE ESTERNA" },
  { id: "759#CALLE ESTRAMURALE", value: "CALLE ESTRAMURALE" },
  { id: "330#CALLE LARGA", value: "CALLE LARGA" },
  { id: "331#CALLE LITORANEA", value: "CALLE LITORANEA" },
  { id: "760#CALLE LUNGA", value: "CALLE LUNGA" },
  { id: "332#CALLE SINISTRA", value: "CALLE SINISTRA" },
  { id: "333#CALLE STRETTA", value: "CALLE STRETTA" },
  { id: "761#CALLE VECCHIA", value: "CALLE VECCHIA" },
  { id: "30#CALLESELLA", value: "CALLESELLA" },
  { id: "334#CALLESELLA DESTRA", value: "CALLESELLA DESTRA" },
  { id: "335#CALLESELLA LARGA", value: "CALLESELLA LARGA" },
  { id: "336#CALLESELLA SINISTRA", value: "CALLESELLA SINISTRA" },
  { id: "337#CALLESELLE", value: "CALLESELLE" },
  { id: "338#CALLESELLE LARGHE", value: "CALLESELLE LARGHE" },
  { id: "339#CALLESELLE STRETTE", value: "CALLESELLE STRETTE" },
  { id: "762#CALLETTA", value: "CALLETTA" },
  { id: "763#CALLETTA LARGA", value: "CALLETTA LARGA" },
  { id: "764#CALLETTA STRETTA", value: "CALLETTA STRETTA" },
  { id: "765#CAMPALTO", value: "CAMPALTO" },
  { id: "32#CAMPASSO", value: "CAMPASSO" },
  { id: "34#CAMPAZZO", value: "CAMPAZZO" },
  { id: "36#CAMPIELLO", value: "CAMPIELLO" },
  { id: "38#CAMPO", value: "CAMPO" },
  { id: "340#CANALE", value: "CANALE" },
  { id: "341#CANALE LARGO", value: "CANALE LARGO" },
  { id: "342#CANTO", value: "CANTO" },
  { id: "343#CANTONE", value: "CANTONE" },
  { id: "344#CAPO", value: "CAPO" },
  { id: "766#CAPO DI PIAZZA", value: "CAPO DI PIAZZA" },
  { id: "345#CARRARA", value: "CARRARA" },
  { id: "767#CASA", value: "CASA" },
  { id: "40#CASALE", value: "CASALE" },
  { id: "768#CASALI", value: "CASALI" },
  { id: "346#CASCINA", value: "CASCINA" },
  { id: "769#CASCINALI", value: "CASCINALI" },
  { id: "770#CASCINE", value: "CASCINE" },
  { id: "771#CASCINETTA", value: "CASCINETTA" },
  { id: "42#CASE", value: "CASE" },
  { id: "347#CASE SPARSE", value: "CASE SPARSE" },
  { id: "772#CASEGGIATO", value: "CASEGGIATO" },
  { id: "44#CAVA", value: "CAVA" },
  { id: "46#CAVALCAVIA", value: "CAVALCAVIA" },
  { id: "348#CAVALCAVIA DESTRO", value: "CAVALCAVIA DESTRO" },
  { id: "349#CAVALCAVIA SINISTRO", value: "CAVALCAVIA SINISTRO" },
  { id: "350#CAVONE", value: "CAVONE" },
  { id: "51#CDA", value: "CDA" },
  { id: "773#CENTRO", value: "CENTRO" },
  { id: "351#CHIASSETTO", value: "CHIASSETTO" },
  { id: "48#CHIASSO", value: "CHIASSO" },
  { id: "352#CHIASSUOLO", value: "CHIASSUOLO" },
  { id: "774#CIMA", value: "CIMA" },
  { id: "50#CIRCONVALLAZIONE", value: "CIRCONVALLAZIONE" },
  { id: "353#CIRCONVALLAZIONE DESTRA", value: "CIRCONVALLAZIONE DESTRA" },
  { id: "354#CIRCONVALLAZIONE ESTERNA", value: "CIRCONVALLAZIONE ESTERNA" },
  {
    id: "355#CIRCONVALLAZIONE ESTRAMURALE",
    value: "CIRCONVALLAZIONE ESTRAMURALE",
  },
  { id: "356#CIRCONVALLAZIONE INTERNA", value: "CIRCONVALLAZIONE INTERNA" },
  { id: "357#CIRCONVALLAZIONE SINISTRA", value: "CIRCONVALLAZIONE SINISTRA" },
  { id: "775#CIRCUMVALLAZIONE", value: "CIRCUMVALLAZIONE" },
  { id: "776#CIRCUMVALLAZIONE ESTERNA", value: "CIRCUMVALLAZIONE ESTERNA" },
  { id: "358#CLAUSTRO", value: "CLAUSTRO" },
  { id: "52#CLIVIO", value: "CLIVIO" },
  { id: "359#CLIVO", value: "CLIVO" },
  { id: "704#COLLE", value: "COLLE" },
  { id: "360#COMUNALE", value: "COMUNALE" },
  { id: "777#CONDOMINIO", value: "CONDOMINIO" },
  { id: "361#CONTRA'", value: "CONTRA'" },
  { id: "54#CONTRADA", value: "CONTRADA" },
  { id: "778#COOPERATIVA", value: "COOPERATIVA" },
  { id: "362#CORO", value: "CORO" },
  { id: "56#CORSETTO", value: "CORSETTO" },
  { id: "363#CORSIA", value: "CORSIA" },
  { id: "364#CORSIA DESTRA", value: "CORSIA DESTRA" },
  { id: "365#CORSIA SINISTRA", value: "CORSIA SINISTRA" },
  { id: "58#CORSO", value: "CORSO" },
  { id: "366#CORSO PARALLELO", value: "CORSO PARALLELO" },
  { id: "60#CORTE", value: "CORTE" },
  { id: "779#CORTI", value: "CORTI" },
  { id: "62#CORTICELLA", value: "CORTICELLA" },
  { id: "64#CORTILE", value: "CORTILE" },
  { id: "367#CORTINA", value: "CORTINA" },
  { id: "368#COSTA", value: "COSTA" },
  { id: "369#COSTARELLA", value: "COSTARELLA" },
  { id: "781#CROCEVIA", value: "CROCEVIA" },
  { id: "370#CROSA", value: "CROSA" },
  { id: "371#CROSINO", value: "CROSINO" },
  { id: "35#CSO", value: "CSO" },
  { id: "66#CUPA", value: "CUPA" },
  { id: "372#DARSENA", value: "DARSENA" },
  { id: "782#DEVIAZIONE", value: "DEVIAZIONE" },
  { id: "783#DIGA", value: "DIGA" },
  { id: "68#DIRAMAZIONE", value: "DIRAMAZIONE" },
  { id: "373#DIRAMAZIONE DEL CORSO", value: "DIRAMAZIONE DEL CORSO" },
  { id: "374#DIRAMAZIONE DEL VIALE", value: "DIRAMAZIONE DEL VIALE" },
  { id: "784#DIRAMAZIONE DI STRADA", value: "DIRAMAZIONE DI STRADA" },
  { id: "375#DIRAMAZIONE DI VIA", value: "DIRAMAZIONE DI VIA" },
  { id: "785#DIRAMAZIONE DI VICO", value: "DIRAMAZIONE DI VICO" },
  { id: "786#DIRAMAZIONI", value: "DIRAMAZIONI" },
  { id: "377#DIRUPO", value: "DIRUPO" },
  { id: "70#DISCESA", value: "DISCESA" },
  { id: "378#DISTACCO", value: "DISTACCO" },
  { id: "379#DORSO", value: "DORSO" },
  { id: "380#EMICICLO", value: "EMICICLO" },
  { id: "381#ERTA", value: "ERTA" },
  { id: "23#FCE", value: "FCE" },
  { id: "72#FONDACO", value: "FONDACO" },
  { id: "74#FONDAMENTA", value: "FONDAMENTA" },
  { id: "76#FONDO", value: "FONDO" },
  { id: "787#FONTEGO", value: "FONTEGO" },
  { id: "262#FORO", value: "FORO" },
  { id: "382#FORTE", value: "FORTE" },
  { id: "383#FOSSA", value: "FOSSA" },
  { id: "384#FOSSATO", value: "FOSSATO" },
  { id: "385#FOSSO", value: "FOSSO" },
  { id: "3#FRAZ.", value: "FRAZ." },
  { id: "77#FRAZIONE", value: "FRAZIONE" },
  { id: "43#FRN", value: "FRN" },
  { id: "39#GAL", value: "GAL" },
  { id: "78#GALLERIA", value: "GALLERIA" },
  { id: "386#GALLERIA DI CORSO", value: "GALLERIA DI CORSO" },
  { id: "712#GALLERIA PRIVATA", value: "GALLERIA PRIVATA" },
  { id: "788#GIARDINI", value: "GIARDINI" },
  { id: "789#GIARDINI PUBBLICI", value: "GIARDINI PUBBLICI" },
  { id: "80#GIARDINO", value: "GIARDINO" },
  { id: "790#GIARDINO PUBBLICO", value: "GIARDINO PUBBLICO" },
  { id: "387#GRADINATA", value: "GRADINATA" },
  { id: "388#GRADINATA DESTRA", value: "GRADINATA DESTRA" },
  { id: "389#GRADINATA SINISTRA", value: "GRADINATA SINISTRA" },
  { id: "390#GRADINATA SUPERIORE", value: "GRADINATA SUPERIORE" },
  { id: "391#GRADINATE", value: "GRADINATE" },
  { id: "392#GRADINATE SUPERIORI", value: "GRADINATE SUPERIORI" },
  { id: "82#GRADINI", value: "GRADINI" },
  { id: "84#GRADONI", value: "GRADONI" },
  { id: "393#GRANVIALE", value: "GRANVIALE" },
  { id: "791#INCROCIO", value: "INCROCIO" },
  { id: "792#INTERRATO", value: "INTERRATO" },
  { id: "793#ISOLA", value: "ISOLA" },
  { id: "794#ISOLATO", value: "ISOLATO" },
  { id: "47#L.GO", value: "L.GO" },
  { id: "394#LARGHETTO", value: "LARGHETTO" },
  { id: "86#LARGO", value: "LARGO" },
  { id: "713#LARGO PRIVATO", value: "LARGO PRIVATO" },
  { id: "395#LATERALE DI CORSO", value: "LATERALE DI CORSO" },
  { id: "396#LATERALE DI VIA", value: "LATERALE DI VIA" },
  { id: "397#LATERALE DI VIALE", value: "LATERALE DI VIALE" },
  { id: "61#LGO", value: "LGO" },
  { id: "398#LIDO", value: "LIDO" },
  { id: "88#LISTA", value: "LISTA" },
  { id: "5#LOC", value: "LOC" },
  { id: "7#LOC.", value: "LOC." },
  { id: "90#LOCALITA'", value: "LOCALITA'" },
  { id: "33#LOCALITA`", value: "LOCALITA`" },
  { id: "92#LOGGE", value: "LOGGE" },
  { id: "399#LOGGIA", value: "LOGGIA" },
  { id: "795#LOTTIZZAZIONE", value: "LOTTIZZAZIONE" },
  { id: "796#LOTTO", value: "LOTTO" },
  { id: "94#LUNGADIGE", value: "LUNGADIGE" },
  { id: "400#LUNGADIGE DESTRO", value: "LUNGADIGE DESTRO" },
  { id: "401#LUNGADIGE SINISTRO", value: "LUNGADIGE SINISTRO" },
  { id: "96#LUNGARGINE", value: "LUNGARGINE" },
  { id: "402#LUNGARGINE DESTRO", value: "LUNGARGINE DESTRO" },
  { id: "403#LUNGARGINE SINISTRO", value: "LUNGARGINE SINISTRO" },
  { id: "98#LUNGARNO", value: "LUNGARNO" },
  { id: "404#LUNGARNO DESTRO", value: "LUNGARNO DESTRO" },
  { id: "405#LUNGARNO SINISTRO", value: "LUNGARNO SINISTRO" },
  { id: "710#LUNGO", value: "LUNGO" },
  { id: "798#LUNGO ADDA", value: "LUNGO ADDA" },
  { id: "800#LUNGO AGNO", value: "LUNGO AGNO" },
  { id: "802#LUNGO BISAGNO", value: "LUNGO BISAGNO" },
  { id: "804#LUNGO DORA", value: "LUNGO DORA" },
  { id: "805#LUNGO FIUME", value: "LUNGO FIUME" },
  { id: "806#LUNGO FRODOLFO", value: "LUNGO FRODOLFO" },
  { id: "807#LUNGO GESSO", value: "LUNGO GESSO" },
  { id: "811#LUNGO ISONZO", value: "LUNGO ISONZO" },
  { id: "812#LUNGO LAGO", value: "LUNGO LAGO" },
  { id: "813#LUNGO LARIO", value: "LUNGO LARIO" },
  { id: "817#LUNGO LINEA", value: "LUNGO LINEA" },
  { id: "819#LUNGO MALONE", value: "LUNGO MALONE" },
  { id: "820#LUNGO MARE", value: "LUNGO MARE" },
  { id: "821#LUNGO MAZARO", value: "LUNGO MAZARO" },
  { id: "822#LUNGO MOLO", value: "LUNGO MOLO" },
  { id: "823#LUNGO OLONA", value: "LUNGO OLONA" },
  { id: "825#LUNGO PO", value: "LUNGO PO" },
  { id: "826#LUNGO PORTO", value: "LUNGO PORTO" },
  { id: "827#LUNGO SILE", value: "LUNGO SILE" },
  { id: "828#LUNGO STURA", value: "LUNGO STURA" },
  { id: "830#LUNGO TANARO", value: "LUNGO TANARO" },
  { id: "831#LUNGO TEVERE", value: "LUNGO TEVERE" },
  { id: "406#LUNGOBISAGNO", value: "LUNGOBISAGNO" },
  { id: "407#LUNGOBISAGNO DESTRO", value: "LUNGOBISAGNO DESTRO" },
  { id: "408#LUNGOBISAGNO SINISTRO", value: "LUNGOBISAGNO SINISTRO" },
  { id: "409#LUNGOCRATI", value: "LUNGOCRATI" },
  { id: "410#LUNGOCRATI DESTRO", value: "LUNGOCRATI DESTRO" },
  { id: "411#LUNGOCRATI SINISTRO", value: "LUNGOCRATI SINISTRO" },
  { id: "100#LUNGODORA", value: "LUNGODORA" },
  { id: "412#LUNGODORA DESTRO", value: "LUNGODORA DESTRO" },
  { id: "413#LUNGODORA SINISTRO", value: "LUNGODORA SINISTRO" },
  { id: "414#LUNGOFRIGIDO", value: "LUNGOFRIGIDO" },
  { id: "415#LUNGOFRIGIDO DESTRO", value: "LUNGOFRIGIDO DESTRO" },
  { id: "416#LUNGOFRIGIDO SINISTRO", value: "LUNGOFRIGIDO SINISTRO" },
  { id: "417#LUNGOGESSO", value: "LUNGOGESSO" },
  { id: "418#LUNGOGESSO DESTRO", value: "LUNGOGESSO DESTRO" },
  { id: "419#LUNGOGESSO SINISTRO", value: "LUNGOGESSO SINISTRO" },
  { id: "420#LUNGOISARCO", value: "LUNGOISARCO" },
  { id: "421#LUNGOISARCO DESTRO", value: "LUNGOISARCO DESTRO" },
  { id: "422#LUNGOISARCO SINISTRO", value: "LUNGOISARCO SINISTRO" },
  { id: "423#LUNGOLAGO", value: "LUNGOLAGO" },
  { id: "424#LUNGOLAGO DESTRO", value: "LUNGOLAGO DESTRO" },
  { id: "425#LUNGOLAGO SINISTRO", value: "LUNGOLAGO SINISTRO" },
  { id: "426#LUNGOLARIO", value: "LUNGOLARIO" },
  { id: "427#LUNGOLARIO DESTRO", value: "LUNGOLARIO DESTRO" },
  { id: "428#LUNGOLARIO SINISTRO", value: "LUNGOLARIO SINISTRO" },
  { id: "429#LUNGOMALLERO", value: "LUNGOMALLERO" },
  { id: "430#LUNGOMALLERO DESTRO", value: "LUNGOMALLERO DESTRO" },
  { id: "102#LUNGOMARE", value: "LUNGOMARE" },
  { id: "839#LUNGONERA", value: "LUNGONERA" },
  { id: "431#LUNGOPARCO", value: "LUNGOPARCO" },
  { id: "106#LUNGOPO", value: "LUNGOPO" },
  { id: "432#LUNGOPO DESTRO", value: "LUNGOPO DESTRO" },
  { id: "433#LUNGOPO SINISTRO", value: "LUNGOPO SINISTRO" },
  { id: "840#LUNGOSABATO", value: "LUNGOSABATO" },
  { id: "108#LUNGOSTURA", value: "LUNGOSTURA" },
  { id: "434#LUNGOSTURA DESTRO", value: "LUNGOSTURA DESTRO" },
  { id: "435#LUNGOSTURA SINISTRO", value: "LUNGOSTURA SINISTRO" },
  { id: "436#LUNGOTALVERE", value: "LUNGOTALVERE" },
  { id: "437#LUNGOTALVERE DESTRO", value: "LUNGOTALVERE DESTRO" },
  { id: "438#LUNGOTALVERE SINISTRO", value: "LUNGOTALVERE SINISTRO" },
  { id: "842#LUNGOTANARO", value: "LUNGOTANARO" },
  { id: "110#LUNGOTEVERE", value: "LUNGOTEVERE" },
  { id: "439#LUNGOTEVERE DESTRO", value: "LUNGOTEVERE DESTRO" },
  { id: "440#LUNGOTEVERE SINISTRO", value: "LUNGOTEVERE SINISTRO" },
  { id: "441#LUNGOTICINO", value: "LUNGOTICINO" },
  { id: "442#LUNGOTICINO DESTRO", value: "LUNGOTICINO DESTRO" },
  { id: "443#LUNGOTICINO SINISTRO", value: "LUNGOTICINO SINISTRO" },
  { id: "444#LUNGOTORRENTE", value: "LUNGOTORRENTE" },
  { id: "445#LUNGOTORRENTE DESTRO", value: "LUNGOTORRENTE DESTRO" },
  { id: "446#LUNGOTORRENTE SINISTRO", value: "LUNGOTORRENTE SINISTRO" },
  { id: "447#LUNGOTRONTO", value: "LUNGOTRONTO" },
  { id: "448#LUNGOTRONTO DESTRO", value: "LUNGOTRONTO DESTRO" },
  { id: "449#LUNGOTRONTO SINISTRO", value: "LUNGOTRONTO SINISTRO" },
  { id: "450#MARZARIA", value: "MARZARIA" },
  { id: "112#MASSERIA", value: "MASSERIA" },
  { id: "451#MASSERIA VECCHIA", value: "MASSERIA VECCHIA" },
  { id: "114#MERCATO", value: "MERCATO" },
  { id: "452#MERCERIA", value: "MERCERIA" },
  { id: "116#MOLO", value: "MOLO" },
  { id: "453#MOLO ANTICO", value: "MOLO ANTICO" },
  { id: "843#MONTE", value: "MONTE" },
  { id: "118#MULATTIERA", value: "MULATTIERA" },
  { id: "120#MURA", value: "MURA" },
  { id: "454#MURAZZI", value: "MURAZZI" },
  { id: "455#MURE", value: "MURE" },
  { id: "844#NUCLEO", value: "NUCLEO" },
  { id: "29#P.LE", value: "P.LE" },
  { id: "13#P.TTA", value: "P.TTA" },
  { id: "19#P.ZZA", value: "P.ZZA" },
  { id: "845#PALAZZO", value: "PALAZZO" },
  { id: "456#PARALLELA DESTRA", value: "PARALLELA DESTRA" },
  { id: "457#PARALLELA SINISTRA", value: "PARALLELA SINISTRA" },
  { id: "122#PARCO", value: "PARCO" },
  { id: "124#PASSAGGIO", value: "PASSAGGIO" },
  { id: "846#PASSAGGIO PRIVATO", value: "PASSAGGIO PRIVATO" },
  { id: "126#PASSEGGIATA", value: "PASSEGGIATA" },
  { id: "458#PASSEGGIO", value: "PASSEGGIO" },
  { id: "128#PASSETTO", value: "PASSETTO" },
  { id: "260#PASSO", value: "PASSO" },
  { id: "708#PASSO PRIVATO", value: "PASSO PRIVATO" },
  { id: "459#PENDICE", value: "PENDICE" },
  { id: "714#PENDINO", value: "PENDINO" },
  { id: "460#PENDIO", value: "PENDIO" },
  { id: "715#PENNINATA", value: "PENNINATA" },
  { id: "461#PENNINATO", value: "PENNINATO" },
  { id: "848#PESCARIA", value: "PESCARIA" },
  { id: "462#PIAGGIA", value: "PIAGGIA" },
  { id: "463#PIANO", value: "PIANO" },
  { id: "464#PIATTAFORMA", value: "PIATTAFORMA" },
  { id: "130#PIAZZA", value: "PIAZZA" },
  { id: "465#PIAZZA BELVEDERE", value: "PIAZZA BELVEDERE" },
  { id: "466#PIAZZA CHIUSA", value: "PIAZZA CHIUSA" },
  { id: "467#PIAZZA COMUNALE", value: "PIAZZA COMUNALE" },
  { id: "468#PIAZZA INFERIORE", value: "PIAZZA INFERIORE" },
  { id: "849#PIAZZA PRIVATA", value: "PIAZZA PRIVATA" },
  { id: "850#PIAZZA SUPERIORE", value: "PIAZZA SUPERIORE" },
  { id: "132#PIAZZALE", value: "PIAZZALE" },
  { id: "134#PIAZZETTA", value: "PIAZZETTA" },
  { id: "851#PIAZZETTA PRIVATA", value: "PIAZZETTA PRIVATA" },
  { id: "469#PIAZZOLA", value: "PIAZZOLA" },
  { id: "852#PINETA", value: "PINETA" },
  { id: "136#PISCINA", value: "PISCINA" },
  { id: "65#PISTA", value: "PISTA" },
  { id: "470#PLACE", value: "PLACE" },
  { id: "101#PLE", value: "PLE" },
  { id: "707#PODERE", value: "PODERE" },
  { id: "471#POGGIO", value: "POGGIO" },
  { id: "138#PONTE", value: "PONTE" },
  { id: "853#PONTE MONUMENTALE", value: "PONTE MONUMENTALE" },
  { id: "854#PONTI PRIVATI", value: "PONTI PRIVATI" },
  { id: "140#PONTILE", value: "PONTILE" },
  { id: "142#PORTA", value: "PORTA" },
  { id: "472#PORTELLA", value: "PORTELLA" },
  { id: "473#PORTICATO", value: "PORTICATO" },
  { id: "474#PORTICCIOLO", value: "PORTICCIOLO" },
  { id: "475#PORTICHETTI", value: "PORTICHETTI" },
  { id: "476#PORTICI", value: "PORTICI" },
  { id: "144#PORTICO", value: "PORTICO" },
  { id: "146#PORTO", value: "PORTO" },
  { id: "477#PRATO", value: "PRATO" },
  { id: "855#PREDIO", value: "PREDIO" },
  { id: "148#PROLUNGAMENTO", value: "PROLUNGAMENTO" },
  { id: "479#PROLUNGAMENTO DEL VIALE", value: "PROLUNGAMENTO DEL VIALE" },
  { id: "480#PROLUNGAMENTO DELLA VIA", value: "PROLUNGAMENTO DELLA VIA" },
  { id: "478#PROLUNGAMENTO DI CORSO", value: "PROLUNGAMENTO DI CORSO" },
  { id: "856#PROLUNGAMENTO DI VIA", value: "PROLUNGAMENTO DI VIA" },
  { id: "857#PROLUNGAMENTO DI VIALE", value: "PROLUNGAMENTO DI VIALE" },
  { id: "481#PROVINCIALE", value: "PROVINCIALE" },
  { id: "99#PTA", value: "PTA" },
  { id: "9#PZA", value: "PZA" },
  { id: "63#PZT", value: "PZT" },
  { id: "482#QUADRATO", value: "QUADRATO" },
  { id: "858#QUADRIVIO", value: "QUADRIVIO" },
  { id: "150#QUARTIERE", value: "QUARTIERE" },
  { id: "266#RACCORDO", value: "RACCORDO" },
  { id: "859#RACCORDO DI STRADA", value: "RACCORDO DI STRADA" },
  { id: "860#RADA", value: "RADA" },
  { id: "861#RAGGIO", value: "RAGGIO" },
  { id: "152#RAMI", value: "RAMI" },
  { id: "154#RAMO", value: "RAMO" },
  { id: "862#RAMO DI VIA", value: "RAMO DI VIA" },
  { id: "156#RAMPA", value: "RAMPA" },
  { id: "483#RAMPA DEL CORSO", value: "RAMPA DEL CORSO" },
  { id: "484#RAMPA DEL VIALE", value: "RAMPA DEL VIALE" },
  { id: "487#RAMPA DESTRA", value: "RAMPA DESTRA" },
  { id: "863#RAMPA DI VIALE", value: "RAMPA DI VIALE" },
  { id: "485#RAMPA PIAZZA", value: "RAMPA PIAZZA" },
  { id: "488#RAMPA SINISTRA", value: "RAMPA SINISTRA" },
  { id: "489#RAMPA STRADA", value: "RAMPA STRADA" },
  { id: "486#RAMPA VIA", value: "RAMPA VIA" },
  { id: "158#RAMPE", value: "RAMPE" },
  { id: "59#RDA", value: "RDA" },
  { id: "160#RECINTO", value: "RECINTO" },
  { id: "706#REGIONE", value: "REGIONE" },
  { id: "864#RESIDENCE", value: "RESIDENCE" },
  { id: "865#RESIDENZA", value: "RESIDENZA" },
  { id: "490#RIALTO", value: "RIALTO" },
  { id: "491#RIGASTE", value: "RIGASTE" },
  { id: "492#RIO", value: "RIO" },
  { id: "867#RIO TERA'", value: "RIO TERA'" },
  { id: "493#RIO TERRA'", value: "RIO TERRA'" },
  { id: "162#RIONE", value: "RIONE" },
  { id: "868#RIONE NUOVO", value: "RIONE NUOVO" },
  { id: "264#RIPA", value: "RIPA" },
  { id: "494#RIPARTO", value: "RIPARTO" },
  { id: "164#RIVA", value: "RIVA" },
  { id: "869#RIVALE", value: "RIVALE" },
  { id: "495#RIVETTA", value: "RIVETTA" },
  { id: "166#RIVIERA", value: "RIVIERA" },
  { id: "496#RONCO", value: "RONCO" },
  { id: "871#RONCO A VIA", value: "RONCO A VIA" },
  { id: "872#RONCO AL CORSO", value: "RONCO AL CORSO" },
  { id: "873#RONCO AL VIALE", value: "RONCO AL VIALE" },
  { id: "497#RONDO", value: "RONDO" },
  { id: "874#RONDO'", value: "RONDO'" },
  { id: "168#ROTONDA", value: "ROTONDA" },
  { id: "498#ROUTE", value: "ROUTE" },
  { id: "55#RRI", value: "RRI" },
  { id: "170#RUA", value: "RUA" },
  { id: "499#RUE", value: "RUE" },
  { id: "500#RUGA", value: "RUGA" },
  { id: "501#RUGA DESTRA", value: "RUGA DESTRA" },
  { id: "502#RUGA SINISTRA", value: "RUGA SINISTRA" },
  { id: "875#RUGA VECCHIA", value: "RUGA VECCHIA" },
  { id: "503#RUGHETTA", value: "RUGHETTA" },
  { id: "504#RUGHETTA DESTRA", value: "RUGHETTA DESTRA" },
  { id: "505#RUGHETTA SINISTRA", value: "RUGHETTA SINISTRA" },
  { id: "45#S.S", value: "S.S" },
  { id: "876#SACCA", value: "SACCA" },
  { id: "877#SAGRATO", value: "SAGRATO" },
  { id: "172#SALITA", value: "SALITA" },
  { id: "506#SALITA DESTRA", value: "SALITA DESTRA" },
  { id: "709#SALITA INFERIORE", value: "SALITA INFERIORE" },
  { id: "878#SALITA NUOVA", value: "SALITA NUOVA" },
  { id: "507#SALITA PER CORSO", value: "SALITA PER CORSO" },
  { id: "508#SALITA PER PIAZZA", value: "SALITA PER PIAZZA" },
  { id: "509#SALITA PER VIA", value: "SALITA PER VIA" },
  { id: "510#SALITA PER VIALE", value: "SALITA PER VIALE" },
  { id: "511#SALITA SINISTRA", value: "SALITA SINISTRA" },
  { id: "512#SALITA SUPERIORE", value: "SALITA SUPERIORE" },
  { id: "879#SALITA VECCHIA", value: "SALITA VECCHIA" },
  { id: "880#SALIZADA", value: "SALIZADA" },
  { id: "514#SALIZADA SINISTRA", value: "SALIZADA SINISTRA" },
  { id: "176#SALIZZATA", value: "SALIZZATA" },
  { id: "513#SALIZZATA DESTRA", value: "SALIZZATA DESTRA" },
  { id: "515#SBARCATOIO", value: "SBARCATOIO" },
  { id: "178#SCALA", value: "SCALA" },
  { id: "516#SCALA DESTRA", value: "SCALA DESTRA" },
  { id: "517#SCALA SINISTRA", value: "SCALA SINISTRA" },
  { id: "180#SCALE", value: "SCALE" },
  { id: "182#SCALEA", value: "SCALEA" },
  { id: "518#SCALEO", value: "SCALEO" },
  { id: "184#SCALETTA", value: "SCALETTA" },
  { id: "519#SCALETTA DESTRA", value: "SCALETTA DESTRA" },
  { id: "520#SCALETTA SINISTRA", value: "SCALETTA SINISTRA" },
  { id: "186#SCALETTE", value: "SCALETTE" },
  { id: "188#SCALI", value: "SCALI" },
  { id: "190#SCALINATA", value: "SCALINATA" },
  { id: "881#SCALINATA A SALITA", value: "SCALINATA A SALITA" },
  { id: "882#SCALINATA A VIA", value: "SCALINATA A VIA" },
  { id: "883#SCALINATA CHIUSA", value: "SCALINATA CHIUSA" },
  { id: "521#SCALINATA DESTRA", value: "SCALINATA DESTRA" },
  { id: "884#SCALINATA PRIVATA", value: "SCALINATA PRIVATA" },
  { id: "522#SCALINATA SINISTRA", value: "SCALINATA SINISTRA" },
  { id: "523#SCALO", value: "SCALO" },
  { id: "192#SCALONE", value: "SCALONE" },
  { id: "524#SCESA", value: "SCESA" },
  { id: "525#SCESE", value: "SCESE" },
  { id: "57#SDR", value: "SDR" },
  { id: "194#SDRUCCIOLO", value: "SDRUCCIOLO" },
  { id: "885#SECCO", value: "SECCO" },
  { id: "526#SELCIATO", value: "SELCIATO" },
  { id: "196#SENTIERO", value: "SENTIERO" },
  { id: "527#SENTIERO PANORAMICO", value: "SENTIERO PANORAMICO" },
  { id: "528#SESTIERE", value: "SESTIERE" },
  { id: "198#SESTRIERI", value: "SESTRIERI" },
  { id: "200#SITO", value: "SITO" },
  { id: "174#SL", value: "SL" },
  { id: "37#SNE", value: "SNE" },
  { id: "202#SOBBORGO", value: "SOBBORGO" },
  { id: "529#SOTTOPASSAGGI", value: "SOTTOPASSAGGI" },
  { id: "530#SOTTOPASSAGGIO", value: "SOTTOPASSAGGIO" },
  { id: "886#SOTTOPASSAGGIO DI PIAZZA", value: "SOTTOPASSAGGIO DI PIAZZA" },
  { id: "531#SOTTOPASSO", value: "SOTTOPASSO" },
  { id: "204#SOTTOPORTICO", value: "SOTTOPORTICO" },
  { id: "206#SOTTOVIA", value: "SOTTOVIA" },
  { id: "532#SPALTO", value: "SPALTO" },
  { id: "533#SPIAGGIA", value: "SPIAGGIA" },
  { id: "208#SPIANATA", value: "SPIANATA" },
  { id: "887#SPIAZZI", value: "SPIAZZI" },
  { id: "534#SPIAZZO", value: "SPIAZZO" },
  { id: "535#STATALE", value: "STATALE" },
  { id: "888#STAZIONE", value: "STAZIONE" },
  { id: "536#STAZZO", value: "STAZZO" },
  { id: "25#STR", value: "STR" },
  { id: "210#STRADA", value: "STRADA" },
  { id: "537#STRADA ACCORCIATOIA", value: "STRADA ACCORCIATOIA" },
  { id: "538#STRADA ALTA", value: "STRADA ALTA" },
  { id: "539#STRADA ANTICA", value: "STRADA ANTICA" },
  { id: "540#STRADA ARGINALE", value: "STRADA ARGINALE" },
  { id: "541#STRADA BASSA", value: "STRADA BASSA" },
  { id: "542#STRADA CANTONIERA", value: "STRADA CANTONIERA" },
  { id: "543#STRADA CHIUSA", value: "STRADA CHIUSA" },
  { id: "544#STRADA CIECA", value: "STRADA CIECA" },
  { id: "545#STRADA CIRCOLARE", value: "STRADA CIRCOLARE" },
  { id: "546#STRADA COMUNALE", value: "STRADA COMUNALE" },
  { id: "889#STRADA CONSOLARE", value: "STRADA CONSOLARE" },
  { id: "890#STRADA CONSORTILE", value: "STRADA CONSORTILE" },
  { id: "547#STRADA CONSORZIALE", value: "STRADA CONSORZIALE" },
  { id: "548#STRADA DESTRA", value: "STRADA DESTRA" },
  { id: "549#STRADA DI LEVANTE", value: "STRADA DI LEVANTE" },
  { id: "550#STRADA DI PONENTE", value: "STRADA DI PONENTE" },
  { id: "891#STRADA DIETRO", value: "STRADA DIETRO" },
  { id: "551#STRADA ESTERNA", value: "STRADA ESTERNA" },
  { id: "552#STRADA EXTRAMURALE", value: "STRADA EXTRAMURALE" },
  { id: "553#STRADA INFERIORE", value: "STRADA INFERIORE" },
  { id: "554#STRADA INTERCOMUNALE", value: "STRADA INTERCOMUNALE" },
  { id: "555#STRADA INTERNA", value: "STRADA INTERNA" },
  { id: "556#STRADA INTERPODERALE", value: "STRADA INTERPODERALE" },
  { id: "557#STRADA LARGA", value: "STRADA LARGA" },
  { id: "558#STRADA LATERALE", value: "STRADA LATERALE" },
  { id: "559#STRADA LITORANEA", value: "STRADA LITORANEA" },
  { id: "560#STRADA MULATTIERA", value: "STRADA MULATTIERA" },
  { id: "892#STRADA NAZIONALE", value: "STRADA NAZIONALE" },
  { id: "561#STRADA NUOVA", value: "STRADA NUOVA" },
  { id: "562#STRADA PANORAMICA", value: "STRADA PANORAMICA" },
  { id: "563#STRADA PARALLELA", value: "STRADA PARALLELA" },
  { id: "564#STRADA PEDEMONTANA", value: "STRADA PEDEMONTANA" },
  { id: "893#STRADA PEDONALE", value: "STRADA PEDONALE" },
  { id: "894#STRADA PODERALE", value: "STRADA PODERALE" },
  { id: "895#STRADA PRINCIPALE", value: "STRADA PRINCIPALE" },
  { id: "565#STRADA PRIVATA", value: "STRADA PRIVATA" },
  { id: "896#STRADA PRIVATA DI VIA", value: "STRADA PRIVATA DI VIA" },
  { id: "566#STRADA PROVINCIALE", value: "STRADA PROVINCIALE" },
  { id: "897#STRADA REGIONALE", value: "STRADA REGIONALE" },
  { id: "567#STRADA ROMANA", value: "STRADA ROMANA" },
  { id: "568#STRADA ROTABILE", value: "STRADA ROTABILE" },
  { id: "569#STRADA RURALE", value: "STRADA RURALE" },
  { id: "570#STRADA SINISTRA", value: "STRADA SINISTRA" },
  { id: "571#STRADA STATALE", value: "STRADA STATALE" },
  { id: "572#STRADA STORTA", value: "STRADA STORTA" },
  { id: "573#STRADA STRETTA", value: "STRADA STRETTA" },
  { id: "574#STRADA SUPERIORE", value: "STRADA SUPERIORE" },
  { id: "575#STRADA TANGENZIALE", value: "STRADA TANGENZIALE" },
  { id: "576#STRADA TRASVERSALE", value: "STRADA TRASVERSALE" },
  { id: "577#STRADA TRAVERSA", value: "STRADA TRAVERSA" },
  { id: "578#STRADA VECCHIA", value: "STRADA VECCHIA" },
  { id: "579#STRADA VICINALE", value: "STRADA VICINALE" },
  { id: "212#STRADALE", value: "STRADALE" },
  { id: "214#STRADELLA", value: "STRADELLA" },
  { id: "580#STRADELLA DESTRA", value: "STRADELLA DESTRA" },
  { id: "898#STRADELLA INTERNA", value: "STRADELLA INTERNA" },
  { id: "899#STRADELLA PEDONALE", value: "STRADELLA PEDONALE" },
  { id: "900#STRADELLA PRIVATA", value: "STRADELLA PRIVATA" },
  { id: "581#STRADELLA SINISTRA", value: "STRADELLA SINISTRA" },
  { id: "721#STRADELLO", value: "STRADELLO" },
  { id: "216#STRADONE", value: "STRADONE" },
  { id: "902#STRADONE LUNGO", value: "STRADONE LUNGO" },
  { id: "903#STRETTA", value: "STRETTA" },
  { id: "582#STRETTO", value: "STRETTO" },
  { id: "583#STRETTOIA", value: "STRETTOIA" },
  { id: "584#STRETTOIA DESTRA", value: "STRETTOIA DESTRA" },
  { id: "585#STRETTOIA SINISTRA", value: "STRETTOIA SINISTRA" },
  { id: "586#STRETTOLA", value: "STRETTOLA" },
  { id: "587#STURA", value: "STURA" },
  { id: "588#SUPERSTRADA", value: "SUPERSTRADA" },
  { id: "218#SUPPORTICO", value: "SUPPORTICO" },
  { id: "220#SVINCOLO", value: "SVINCOLO" },
  { id: "904#SVINCOLO DI STRADA STATALE", value: "SVINCOLO DI STRADA STATALE" },
  { id: "720#SVOTO", value: "SVOTO" },
  { id: "589#TANGENZIALE", value: "TANGENZIALE" },
  { id: "905#TENUTA", value: "TENUTA" },
  { id: "590#TERRAZZA", value: "TERRAZZA" },
  { id: "716#TONDO", value: "TONDO" },
  { id: "906#TORRE", value: "TORRE" },
  { id: "907#TORRENTE", value: "TORRENTE" },
  { id: "908#TRASVERSALE", value: "TRASVERSALE" },
  { id: "591#TRASVERSALE DEL CORSO", value: "TRASVERSALE DEL CORSO" },
  { id: "592#TRASVERSALE DI VIALE", value: "TRASVERSALE DI VIALE" },
  { id: "595#TRASVERSALE PROVINCIALE", value: "TRASVERSALE PROVINCIALE" },
  { id: "593#TRASVERSALE VIA", value: "TRASVERSALE VIA" },
  { id: "222#TRATTO", value: "TRATTO" },
  { id: "597#TRATTURO", value: "TRATTURO" },
  { id: "224#TRAVERSA", value: "TRAVERSA" },
  { id: "598#TRAVERSA CORSO", value: "TRAVERSA CORSO" },
  { id: "599#TRAVERSA DEL VIALE", value: "TRAVERSA DEL VIALE" },
  { id: "600#TRAVERSA DEL VILLAGGIO", value: "TRAVERSA DEL VILLAGGIO" },
  { id: "601#TRAVERSA DELLA LOCALITA'", value: "TRAVERSA DELLA LOCALITA'" },
  { id: "910#TRAVERSA DESTRA DI VIA", value: "TRAVERSA DESTRA DI VIA" },
  { id: "911#TRAVERSA DI CORSO", value: "TRAVERSA DI CORSO" },
  { id: "912#TRAVERSA DI LARGO", value: "TRAVERSA DI LARGO" },
  { id: "913#TRAVERSA DI LUNGOMARE", value: "TRAVERSA DI LUNGOMARE" },
  { id: "914#TRAVERSA DI PIAZZA", value: "TRAVERSA DI PIAZZA" },
  { id: "915#TRAVERSA DI PROLUNGAMENTO", value: "TRAVERSA DI PROLUNGAMENTO" },
  { id: "916#TRAVERSA DI SALITA", value: "TRAVERSA DI SALITA" },
  { id: "917#TRAVERSA DI STRADA", value: "TRAVERSA DI STRADA" },
  {
    id: "918#TRAVERSA DI STRADA PROVINCIALE",
    value: "TRAVERSA DI STRADA PROVINCIALE",
  },
  { id: "919#TRAVERSA DI STRADA STATALE", value: "TRAVERSA DI STRADA STATALE" },
  {
    id: "920#TRAVERSA DI STRADA VICINALE",
    value: "TRAVERSA DI STRADA VICINALE",
  },
  { id: "602#TRAVERSA DI VIA", value: "TRAVERSA DI VIA" },
  { id: "921#TRAVERSA DI VIA ESTERNA", value: "TRAVERSA DI VIA ESTERNA" },
  {
    id: "922#TRAVERSA DI VIA ESTRAMURALE",
    value: "TRAVERSA DI VIA ESTRAMURALE",
  },
  { id: "923#TRAVERSA DI VIA INTERNA", value: "TRAVERSA DI VIA INTERNA" },
  { id: "924#TRAVERSA DI VIA PRIVATA", value: "TRAVERSA DI VIA PRIVATA" },
  { id: "925#TRAVERSA DI VIALE", value: "TRAVERSA DI VIALE" },
  { id: "926#TRAVERSA DI VICO", value: "TRAVERSA DI VICO" },
  { id: "927#TRAVERSA DI VICOLO", value: "TRAVERSA DI VICOLO" },
  { id: "928#TRAVERSA INTERNA", value: "TRAVERSA INTERNA" },
  { id: "603#TRAVERSA PRIVATA", value: "TRAVERSA PRIVATA" },
  { id: "604#TRAVERSA STRADA", value: "TRAVERSA STRADA" },
  { id: "930#TRAVERSA ULTIMA", value: "TRAVERSA ULTIMA" },
  { id: "226#TRAVERSA VIA", value: "TRAVERSA VIA" },
  { id: "594#TRAVERSALE PRIVATA", value: "TRAVERSALE PRIVATA" },
  { id: "596#TRAVERSALE STRADA", value: "TRAVERSALE STRADA" },
  { id: "228#TRESANDA", value: "TRESANDA" },
  { id: "230#TRONCO", value: "TRONCO" },
  { id: "21#V.", value: "V." },
  { id: "31#V.LE", value: "V.LE" },
  { id: "17#V.LO", value: "V.LO" },
  { id: "605#VALCO", value: "VALCO" },
  { id: "606#VALICO", value: "VALICO" },
  { id: "607#VALLE", value: "VALLE" },
  { id: "232#VALLONE", value: "VALLONE" },
  { id: "717#VANELLA", value: "VANELLA" },
  { id: "234#VARCO", value: "VARCO" },
  { id: "931#VARIANTE", value: "VARIANTE" },
  { id: "932#VARIANTE DI STRADA STATALE", value: "VARIANTE DI STRADA STATALE" },
  { id: "41#VCO", value: "VCO" },
  { id: "236#VIA", value: "VIA" },
  { id: "608#VIA ACCORCIATOIA", value: "VIA ACCORCIATOIA" },
  { id: "609#VIA ALTA", value: "VIA ALTA" },
  { id: "610#VIA ANTICA", value: "VIA ANTICA" },
  { id: "933#VIA ANTICA PROVINCIALE", value: "VIA ANTICA PROVINCIALE" },
  { id: "611#VIA ARGINALE", value: "VIA ARGINALE" },
  { id: "612#VIA BASSA", value: "VIA BASSA" },
  { id: "613#VIA BELVEDERE", value: "VIA BELVEDERE" },
  { id: "614#VIA CANTONIERA", value: "VIA CANTONIERA" },
  { id: "934#VIA CENTRALE", value: "VIA CENTRALE" },
  { id: "615#VIA CHIUSA", value: "VIA CHIUSA" },
  { id: "616#VIA CIECA", value: "VIA CIECA" },
  { id: "617#VIA CIRCOLARE", value: "VIA CIRCOLARE" },
  { id: "618#VIA CIRCUMVALLAZIONE", value: "VIA CIRCUMVALLAZIONE" },
  { id: "619#VIA COMUNALE", value: "VIA COMUNALE" },
  { id: "935#VIA CONSOLARE", value: "VIA CONSOLARE" },
  { id: "620#VIA CONSORZIALE", value: "VIA CONSORZIALE" },
  { id: "936#VIA CUPA", value: "VIA CUPA" },
  { id: "621#VIA DESTRA", value: "VIA DESTRA" },
  { id: "622#VIA DI LEVANTE", value: "VIA DI LEVANTE" },
  { id: "937#VIA DI PIAZZA", value: "VIA DI PIAZZA" },
  { id: "938#VIA DI PIAZZETTA", value: "VIA DI PIAZZETTA" },
  { id: "623#VIA DI PONENTE", value: "VIA DI PONENTE" },
  { id: "939#VIA ERTA", value: "VIA ERTA" },
  { id: "624#VIA ESTERNA", value: "VIA ESTERNA" },
  { id: "625#VIA ESTRAMURALE", value: "VIA ESTRAMURALE" },
  { id: "626#VIA INFERIORE", value: "VIA INFERIORE" },
  { id: "627#VIA INTERCOMUNALE", value: "VIA INTERCOMUNALE" },
  { id: "628#VIA INTERNA", value: "VIA INTERNA" },
  { id: "629#VIA INTERPODERALE", value: "VIA INTERPODERALE" },
  { id: "630#VIA LARGA", value: "VIA LARGA" },
  { id: "631#VIA LATERALE", value: "VIA LATERALE" },
  { id: "632#VIA LITORANEA", value: "VIA LITORANEA" },
  { id: "633#VIA LUNGOMARE", value: "VIA LUNGOMARE" },
  { id: "634#VIA MULATTIERA", value: "VIA MULATTIERA" },
  { id: "940#VIA NAZIONALE", value: "VIA NAZIONALE" },
  { id: "635#VIA NUOVA", value: "VIA NUOVA" },
  { id: "636#VIA PANORAMICA", value: "VIA PANORAMICA" },
  { id: "637#VIA PARALLELA", value: "VIA PARALLELA" },
  { id: "638#VIA PEDEMONTANA", value: "VIA PEDEMONTANA" },
  { id: "941#VIA PODERALE", value: "VIA PODERALE" },
  { id: "942#VIA PRINCIPALE", value: "VIA PRINCIPALE" },
  { id: "639#VIA PRIVATA", value: "VIA PRIVATA" },
  { id: "640#VIA PROVINCIALE", value: "VIA PROVINCIALE" },
  { id: "943#VIA REGIONALE", value: "VIA REGIONALE" },
  { id: "641#VIA ROMANA", value: "VIA ROMANA" },
  { id: "642#VIA ROTABILE", value: "VIA ROTABILE" },
  { id: "643#VIA RURALE", value: "VIA RURALE" },
  { id: "644#VIA SINISTRA", value: "VIA SINISTRA" },
  { id: "645#VIA STATALE", value: "VIA STATALE" },
  { id: "646#VIA STORTA", value: "VIA STORTA" },
  { id: "647#VIA STRETTA", value: "VIA STRETTA" },
  { id: "648#VIA SUPERIORE", value: "VIA SUPERIORE" },
  { id: "649#VIA TANGENZIALE", value: "VIA TANGENZIALE" },
  { id: "650#VIA TRASVERSALE", value: "VIA TRASVERSALE" },
  { id: "651#VIA TRAVERSA", value: "VIA TRAVERSA" },
  { id: "652#VIA VECCHIA", value: "VIA VECCHIA" },
  { id: "653#VIA VICINALE", value: "VIA VICINALE" },
  { id: "238#VIADOTTO", value: "VIADOTTO" },
  { id: "711#VIAL", value: "VIAL" },
  { id: "240#VIALE", value: "VIALE" },
  { id: "654#VIALE BELVEDERE", value: "VIALE BELVEDERE" },
  { id: "655#VIALE LITORANEO", value: "VIALE LITORANEO" },
  { id: "656#VIALE LUNGOMARE", value: "VIALE LUNGOMARE" },
  { id: "718#VIALE PRIVATO", value: "VIALE PRIVATO" },
  { id: "242#VIALETTO", value: "VIALETTO" },
  { id: "657#VIALONE", value: "VIALONE" },
  { id: "244#VICO", value: "VICO" },
  { id: "658#VICO ALTO", value: "VICO ALTO" },
  { id: "659#VICO BASSO", value: "VICO BASSO" },
  { id: "660#VICO BELVEDERE", value: "VICO BELVEDERE" },
  { id: "945#VICO CENTRALE", value: "VICO CENTRALE" },
  { id: "661#VICO CHIUSO", value: "VICO CHIUSO" },
  { id: "946#VICO CHIUSO DI VIA", value: "VICO CHIUSO DI VIA" },
  { id: "662#VICO CIECO", value: "VICO CIECO" },
  { id: "947#VICO DI VIA", value: "VICO DI VIA" },
  { id: "663#VICO DRITTO", value: "VICO DRITTO" },
  { id: "664#VICO INFERIORE", value: "VICO INFERIORE" },
  { id: "665#VICO LUNGO", value: "VICO LUNGO" },
  { id: "666#VICO NUOVO", value: "VICO NUOVO" },
  { id: "667#VICO PRIVATO", value: "VICO PRIVATO" },
  { id: "719#VICO ROTTO", value: "VICO ROTTO" },
  { id: "668#VICO STORTO", value: "VICO STORTO" },
  { id: "669#VICO STRETTO", value: "VICO STRETTO" },
  { id: "949#VICO SUPERIORE", value: "VICO SUPERIORE" },
  { id: "670#VICO VECCHIO", value: "VICO VECCHIO" },
  { id: "950#VICOLETTI", value: "VICOLETTI" },
  { id: "246#VICOLETTO", value: "VICOLETTO" },
  { id: "671#VICOLETTO CHIUSO", value: "VICOLETTO CHIUSO" },
  { id: "672#VICOLETTO CIECO", value: "VICOLETTO CIECO" },
  { id: "673#VICOLETTO DRITTO", value: "VICOLETTO DRITTO" },
  { id: "674#VICOLETTO INFERIORE", value: "VICOLETTO INFERIORE" },
  { id: "675#VICOLETTO LUNGO", value: "VICOLETTO LUNGO" },
  { id: "676#VICOLETTO NUOVO", value: "VICOLETTO NUOVO" },
  { id: "677#VICOLETTO PRIVATO", value: "VICOLETTO PRIVATO" },
  { id: "678#VICOLETTO STORTO", value: "VICOLETTO STORTO" },
  { id: "679#VICOLETTO STRETTO", value: "VICOLETTO STRETTO" },
  { id: "680#VICOLETTO VECCHIO", value: "VICOLETTO VECCHIO" },
  { id: "248#VICOLO", value: "VICOLO" },
  { id: "681#VICOLO ALTO", value: "VICOLO ALTO" },
  { id: "951#VICOLO ANTICO", value: "VICOLO ANTICO" },
  { id: "682#VICOLO BASSO", value: "VICOLO BASSO" },
  { id: "683#VICOLO BELVEDERE", value: "VICOLO BELVEDERE" },
  { id: "684#VICOLO CHIUSO", value: "VICOLO CHIUSO" },
  { id: "952#VICOLO CHIUSO DI VIA", value: "VICOLO CHIUSO DI VIA" },
  { id: "685#VICOLO CIECO", value: "VICOLO CIECO" },
  { id: "953#VICOLO CORTO", value: "VICOLO CORTO" },
  { id: "954#VICOLO DESTRO", value: "VICOLO DESTRO" },
  { id: "955#VICOLO DI VIA", value: "VICOLO DI VIA" },
  { id: "956#VICOLO DIETRO", value: "VICOLO DIETRO" },
  { id: "686#VICOLO DRITTO", value: "VICOLO DRITTO" },
  { id: "687#VICOLO INFERIORE", value: "VICOLO INFERIORE" },
  { id: "688#VICOLO LUNGO", value: "VICOLO LUNGO" },
  { id: "689#VICOLO NUOVO", value: "VICOLO NUOVO" },
  { id: "690#VICOLO PRIVATO", value: "VICOLO PRIVATO" },
  { id: "957#VICOLO SINISTRO", value: "VICOLO SINISTRO" },
  { id: "691#VICOLO STORTO", value: "VICOLO STORTO" },
  { id: "692#VICOLO STRETTO", value: "VICOLO STRETTO" },
  { id: "693#VICOLO VECCHIO", value: "VICOLO VECCHIO" },
  { id: "694#VIELLA", value: "VIELLA" },
  { id: "695#VIETTA", value: "VIETTA" },
  { id: "958#VILLA", value: "VILLA" },
  { id: "250#VILLAGGIO", value: "VILLAGGIO" },
  { id: "959#VILLETTA", value: "VILLETTA" },
  { id: "960#VILLINI", value: "VILLINI" },
  { id: "961#VILLINO", value: "VILLINO" },
  { id: "963#VIOTTO CIECO", value: "VIOTTO CIECO" },
  { id: "696#VIOTTOLA", value: "VIOTTOLA" },
  { id: "252#VIOTTOLO", value: "VIOTTOLO" },
  { id: "697#VIUZZA", value: "VIUZZA" },
  { id: "254#VIUZZO", value: "VIUZZO" },
  { id: "11#VLE", value: "VLE" },
  { id: "15#VLO", value: "VLO" },
  { id: "256#VO", value: "VO" },
  { id: "698#VO'", value: "VO'" },
  { id: "699#VOCABOLO", value: "VOCABOLO" },
  { id: "964#VOCABOLO DI VIA", value: "VOCABOLO DI VIA" },
  { id: "258#VOLTA", value: "VOLTA" },
  { id: "700#VOLTE", value: "VOLTE" },
  { id: "965#VOLTI", value: "VOLTI" },
  { id: "701#VOLTO", value: "VOLTO" },
  { id: "702#VOLTONE", value: "VOLTONE" },
  { id: "53#VTA", value: "VTA" },
  { id: "703#ZIPA", value: "ZIPA" },
  { id: "705#ZONA", value: "ZONA" },
  { id: "966#ZONA ARTIGIANALE", value: "ZONA ARTIGIANALE" },
  { id: "967#ZONA INDUSTRIALE", value: "ZONA INDUSTRIALE" },
];
